.TH CKON "1" "January 2015" "ckon 0.7.1" "User Commands"
.SH NAME
ckon \- automatic build tool for ROOT analyses
.SH DESCRIPTION
ckon \fB\-\-\fR automatic build tool for ROOT
.SS "Generic Options:"
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
show this help
.TP
\fB\-\-version\fR
print version number
.TP
\fB\-v\fR [ \fB\-\-verbose\fR ]
verbose output
.TP
\fB\-j\fR arg
call make w/ \fB\-j\fR <#cores>
.TP
\fB\-\-ckon_cmd\fR arg
setup | clean | install | dry
.SS "Configuration:"
.TP
\fB\-s\fR [ \fB\-\-suffix\fR ] arg
add suffix + in LinkDef.h (bool)
.TP
\fB\-y\fR [ \fB\-\-yaml\fR ] arg
use yaml
.TP
\fB\-\-ckon\fR.src_dir arg
source dir
.TP
\fB\-\-ckon\fR.exclSuffix arg
no + suffix
.TP
\fB\-\-ckon\fR.NoRootCint arg
no dictionary
.HP
\fB\-\-ckon\fR.prog_subdir arg progs subdir
.TP
\fB\-\-ckon\fR.build_dir arg
build dir
.HP
\fB\-\-ckon\fR.install_dir arg install dir
.TP
\fB\-\-ckon\fR.cppflags arg
add CPPFLAGS
.TP
\fB\-\-ckon\fR.boost arg
boost libraries
.PP
In addition, unregistered options of the form
ldadd.prog_name are allowed to use for adding
LDFLAGS to the linker of specific programs. The
given string/value is added verbatim in LDADD.
Unregistered options are only allowed in ckon.cfg
.SH "SEE ALSO"
https://ckon.readthedocs.org
